import { CompatibilityRecord } from "@/lib/types";

// Starter clinical dataset. This is a general-education reference derived
// from widely known IV compatibility principles. It is NOT a substitute for
// Trissel's Handbook on Injectable Drugs, King Guide, Micromedex, or your
// institution's own P&T-approved protocols, and record-level confidence
// scores should be reviewed by a pharmacist before clinical use. Extend or
// correct via the admin panel.
export const SEED_INTERACTIONS: CompatibilityRecord[] = [
  {
    id: "ceftriaxone_calcium-gluconate",
    drugA: "Ceftriaxone",
    drugB: "Calcium Gluconate",
    status: "incompatible",
    confidenceScore: 97,
    type: "chemical",
    severity: "major",
    mechanism:
      "Ceftriaxone can form an insoluble ceftriaxone-calcium precipitate. Reports of fatal precipitates in neonatal lungs and kidneys led to a black-box style warning against co-administration of ceftriaxone with calcium-containing IV solutions, even via different lines/sites, in neonates.",
    recommendedAction:
      "Do not co-administer ceftriaxone and any calcium-containing IV product in neonates (≤28 days), regardless of infusion site or line. In older patients, avoid simultaneous Y-site administration; if both are required, use separate lines, separate sites, and flush thoroughly between infusions.",
    alternativeAdministration:
      "Space doses and use separate IV access; consider an alternative cephalosporin (e.g., cefotaxime) in neonates and small infants who require IV calcium.",
    flushRecommendation:
      "Flush the line with at least 10-20 mL of 0.9% Sodium Chloride or 5% Dextrose before and after each drug if sequential administration on the same line is unavoidable in non-neonatal patients.",
    ySiteCompatible: false,
    ySiteNotes: "Contraindicated at Y-site in all age groups; absolute contraindication in neonates even on separate lines.",
    concentrationDependent: true,
    concentrationNotes: [
      { drug: "Ceftriaxone", concentration: "Higher concentrations", note: "Increase precipitation risk" },
      { drug: "Calcium Gluconate", concentration: "Higher concentrations", note: "Increase precipitation risk" },
    ],
    careSettings: ["neonates", "pediatrics", "icu", "general"],
    careSettingNotes: {
      neonates: "Absolute contraindication - do not co-administer via any route within 48 hours of each other.",
      pediatrics: "Avoid concurrent administration; use separate lines and confirm timing with pharmacy.",
    },
    references: [
      { source: "ASHP", citation: "Ceftriaxone-calcium precipitation safety communication", year: 2009 },
      { source: "Trissel's IV Compatibility", citation: "Ceftriaxone monograph" },
      { source: "Micromedex", citation: "Ceftriaxone drug interaction data" },
    ],
    lastReviewed: "2025-11-01",
  },
  {
    id: "phenytoin_dextrose-5",
    drugA: "Phenytoin",
    drugB: "Sodium Chloride 0.9%",
    status: "caution",
    confidenceScore: 80,
    type: "physical",
    severity: "moderate",
    mechanism:
      "Phenytoin is highly pH-dependent and prone to precipitation in solutions with pH below ~11.5. It is formulated in a propylene glycol/ethanol vehicle and precipitates when diluted in most IV fluids, particularly dextrose-containing solutions.",
    recommendedAction:
      "Administer phenytoin as a slow IV push through a dedicated line, or dilute only in 0.9% Sodium Chloride (never dextrose) and use an in-line filter, infusing immediately after preparation.",
    alternativeAdministration:
      "Prefer fosphenytoin where available, as it is water-soluble and compatible with a wider range of diluents and infusion rates.",
    flushRecommendation:
      "Flush line with 0.9% Sodium Chloride before and after administration; never flush with dextrose-containing fluids.",
    ySiteCompatible: "conditional",
    ySiteNotes: "Avoid Y-site with most drugs; compatibility is highly diluent- and concentration-dependent.",
    concentrationDependent: true,
    concentrationNotes: [
      { drug: "Phenytoin", concentration: "> 6.7 mg/mL in NS", note: "Increased precipitation risk; use inline filter" },
    ],
    careSettings: ["icu", "pediatrics", "general"],
    references: [
      { source: "Trissel's IV Compatibility", citation: "Phenytoin monograph" },
      { source: "King Guide to Parenteral Admixtures", citation: "Phenytoin sodium" },
    ],
    lastReviewed: "2025-10-12",
  },
  {
    id: "vancomycin_heparin",
    drugA: "Vancomycin",
    drugB: "Heparin Sodium",
    status: "incompatible",
    confidenceScore: 85,
    type: "chemical",
    severity: "moderate",
    mechanism:
      "Vancomycin is a cationic glycopeptide that can complex with anionic heparin, forming a visible precipitate; the risk rises with higher concentrations of either agent.",
    recommendedAction:
      "Avoid Y-site co-infusion. If a central line is heparin-locked, flush thoroughly with 0.9% Sodium Chloride before and after vancomycin administration.",
    alternativeAdministration:
      "Use a separate lumen for vancomycin on multi-lumen central catheters when a heparin infusion is running.",
    flushRecommendation:
      "Flush with 10-20 mL 0.9% Sodium Chloride before and after vancomycin infusion when sharing a line.",
    ySiteCompatible: false,
    concentrationDependent: true,
    careSettings: ["icu", "general"],
    references: [
      { source: "Trissel's IV Compatibility", citation: "Vancomycin-heparin monograph" },
      { source: "Micromedex", citation: "Vancomycin IV compatibility data" },
    ],
    lastReviewed: "2025-09-20",
  },
  {
    id: "furosemide_midazolam",
    drugA: "Furosemide",
    drugB: "Midazolam",
    status: "incompatible",
    confidenceScore: 88,
    type: "physical",
    severity: "moderate",
    mechanism:
      "Furosemide is formulated at an alkaline pH while midazolam injection is formulated at an acidic pH; mixing the two shifts pH toward precipitation of midazolam free base.",
    recommendedAction:
      "Do not mix in the same syringe or Y-site. Administer through separate lines or sequentially with a thorough flush.",
    alternativeAdministration: "Give as separate, sequential IV push/infusions on different access if only one lumen is available.",
    flushRecommendation: "Flush with 0.9% Sodium Chloride between administrations.",
    ySiteCompatible: false,
    concentrationDependent: false,
    careSettings: ["icu", "general"],
    references: [{ source: "Trissel's IV Compatibility", citation: "Furosemide monograph" }],
    lastReviewed: "2025-08-15",
  },
  {
    id: "dopamine_sodium-bicarbonate",
    drugA: "Dopamine",
    drugB: "Sodium Bicarbonate",
    status: "incompatible",
    confidenceScore: 90,
    type: "chemical",
    severity: "major",
    mechanism:
      "Alkaline solutions such as sodium bicarbonate rapidly inactivate catecholamines like dopamine through oxidation, degrading potency and risking sub-therapeutic vasopressor effect.",
    recommendedAction: "Never mix or co-infuse in the same line. Use completely separate IV access for vasopressor infusions.",
    alternativeAdministration: "Run dopamine on a dedicated, clearly labeled central line; administer bicarbonate through a separate lumen.",
    flushRecommendation: "If sequential use on the same line is unavoidable in an emergency, flush thoroughly with 0.9% Sodium Chloride first.",
    ySiteCompatible: false,
    concentrationDependent: false,
    careSettings: ["icu"],
    careSettingNotes: { icu: "Common bedside error during codes - keep pressor lines dedicated and clearly labeled." },
    references: [
      { source: "Trissel's IV Compatibility", citation: "Dopamine monograph" },
      { source: "ASHP", citation: "Vasopressor administration safety guidance" },
    ],
    lastReviewed: "2025-07-05",
  },
  {
    id: "propofol_midazolam",
    drugA: "Propofol",
    drugB: "Midazolam",
    status: "compatible",
    confidenceScore: 82,
    type: "physical",
    severity: "minor",
    mechanism:
      "Both agents are commonly co-administered for procedural sedation; published Y-site compatibility studies show no visible precipitate or significant potency loss over short infusion periods.",
    recommendedAction: "Y-site co-administration is acceptable for short-term sedation with standard monitoring.",
    alternativeAdministration: "No alternative route typically required; continue standard sedation monitoring protocols.",
    flushRecommendation: "Routine line flush with 0.9% Sodium Chloride at the end of sedation is sufficient.",
    ySiteCompatible: true,
    concentrationDependent: false,
    careSettings: ["icu", "general"],
    references: [{ source: "Published Study", citation: "Propofol-midazolam Y-site compatibility study" }],
    lastReviewed: "2025-06-18",
  },
  {
    id: "piperacillin-tazobactam_gentamicin",
    drugA: "Piperacillin-Tazobactam",
    drugB: "Gentamicin",
    status: "incompatible",
    confidenceScore: 92,
    type: "chemical",
    severity: "major",
    mechanism:
      "Penicillins, including piperacillin-tazobactam, can chemically inactivate aminoglycosides such as gentamicin through covalent binding when mixed together, especially in renal-impaired patients or on standing.",
    recommendedAction: "Never mix in the same syringe, bag, or Y-site. Administer through separate lines with adequate temporal separation.",
    alternativeAdministration: "Infuse piperacillin-tazobactam and gentamicin on separate lumens; if only one lumen is available, separate by at least 1 hour with a flush between.",
    flushRecommendation: "Flush with 10-20 mL 0.9% Sodium Chloride between infusions.",
    ySiteCompatible: false,
    concentrationDependent: false,
    careSettings: ["icu", "pediatrics", "neonates", "general"],
    careSettingNotes: { neonates: "Inactivation risk is heightened with prolonged contact time - avoid any shared line." },
    references: [
      { source: "Trissel's IV Compatibility", citation: "Piperacillin-aminoglycoside monograph" },
      { source: "King Guide to Parenteral Admixtures", citation: "Aminoglycoside compatibility" },
    ],
    lastReviewed: "2025-11-20",
  },
  {
    id: "magnesium-sulfate_calcium-gluconate",
    drugA: "Magnesium Sulfate",
    drugB: "Calcium Gluconate",
    status: "caution",
    confidenceScore: 75,
    type: "therapeutic",
    severity: "moderate",
    mechanism:
      "Magnesium and calcium are physically compatible in most diluents at standard concentrations, but calcium is the clinical antidote for magnesium toxicity, so co-infusion can mask or blunt therapeutic monitoring of either electrolyte's effect.",
    recommendedAction: "Physical Y-site mixing is generally acceptable at usual concentrations, but confirm the clinical indication for concurrent use and monitor levels closely, particularly in pre-eclampsia management or neuromuscular monitoring.",
    alternativeAdministration: "If calcium is being given specifically as a magnesium toxicity antidote, use a separate line so titration of each is clear.",
    flushRecommendation: "Standard flush between bags is sufficient if physically compatible per institutional data.",
    ySiteCompatible: "conditional",
    concentrationDependent: true,
    careSettings: ["icu", "oncology", "general"],
    references: [{ source: "Micromedex", citation: "Magnesium sulfate compatibility data" }],
    lastReviewed: "2025-05-02",
  },
  {
    id: "amiodarone_sodium-chloride-0.9",
    drugA: "Amiodarone",
    drugB: "Sodium Chloride 0.9%",
    status: "caution",
    confidenceScore: 78,
    type: "physical",
    severity: "moderate",
    mechanism:
      "Amiodarone premix is stable in Dextrose 5% but shows reduced physical stability and greater adsorption to PVC tubing when diluted in 0.9% Sodium Chloride at low concentrations; also prone to precipitation when mixed at Y-site with alkaline or high-pH drugs.",
    recommendedAction: "Prefer Dextrose 5% as the diluent per manufacturer labeling. Use non-PVC (polyolefin) tubing/bags where available for prolonged infusions.",
    alternativeAdministration: "Administer through a dedicated central line for infusions exceeding 1 hour; use in-line filter per institutional protocol.",
    flushRecommendation: "Flush thoroughly with the same diluent (D5W) before and after co-administered medications.",
    ySiteCompatible: "conditional",
    ySiteNotes: "Compatible with many common ICU drugs at Y-site, but verify against your institution's IV compatibility chart drug-by-drug.",
    concentrationDependent: true,
    concentrationNotes: [{ drug: "Amiodarone", concentration: "< 2 mg/mL in NS", note: "Reduced stability reported" }],
    careSettings: ["icu", "general"],
    references: [
      { source: "Trissel's IV Compatibility", citation: "Amiodarone monograph" },
      { source: "ASHP", citation: "Amiodarone IV administration guidance" },
    ],
    lastReviewed: "2025-10-30",
  },
  {
    id: "insulin-regular_total-parenteral-nutrition",
    drugA: "Insulin Regular (Human)",
    drugB: "Total Parenteral Nutrition (TPN)",
    status: "caution",
    confidenceScore: 70,
    type: "physical",
    severity: "moderate",
    mechanism:
      "Regular insulin can be added directly to TPN admixtures, but a variable proportion adsorbs to the plastic bag and tubing, making the effective delivered dose less predictable than IV push or a separate infusion.",
    recommendedAction: "If added to TPN, use consistent bag/tubing material and monitor glucose closely; many institutions prefer a separate, titratable insulin infusion for tighter control.",
    alternativeAdministration: "Run insulin as a separate infusion via syringe pump for patients needing frequent dose titration (e.g., ICU glycemic protocols).",
    flushRecommendation: "Not applicable when infused within the TPN admixture; prime separate tubing fully if run independently to account for adsorption.",
    ySiteCompatible: "not-applicable",
    concentrationDependent: true,
    careSettings: ["icu", "general"],
    references: [{ source: "King Guide to Parenteral Admixtures", citation: "Insulin-TPN admixture data" }],
    lastReviewed: "2025-04-11",
  },
  {
    id: "cisplatin_sodium-chloride-0.9",
    drugA: "Cisplatin",
    drugB: "Sodium Chloride 0.9%",
    status: "compatible",
    confidenceScore: 93,
    type: "chemical",
    severity: "minor",
    mechanism:
      "Cisplatin requires a chloride-containing diluent (0.9% Sodium Chloride) to remain stable; low-chloride solutions such as Dextrose 5% in water accelerate aquation and degradation of the compound.",
    recommendedAction: "Dilute and infuse only in 0.9% Sodium Chloride (with or without added magnesium/mannitol per protocol); avoid dextrose-only diluents.",
    alternativeAdministration: "Follow institutional chemotherapy hydration protocol; pre- and post-hydration with normal saline is standard.",
    flushRecommendation: "Flush line with 0.9% Sodium Chloride before and after infusion; use a dedicated line per chemotherapy safe-handling policy.",
    ySiteCompatible: "conditional",
    ySiteNotes: "Avoid Y-site with drugs requiring alkaline or dextrose-based diluents; verify institutional oncology compatibility chart.",
    concentrationDependent: true,
    careSettings: ["oncology", "icu"],
    careSettingNotes: { oncology: "Use closed-system transfer devices and follow hazardous drug handling precautions." },
    references: [
      { source: "Trissel's IV Compatibility", citation: "Cisplatin monograph" },
      { source: "ASHP", citation: "Cisplatin handling and administration guidance" },
    ],
    lastReviewed: "2025-09-02",
  },
  {
    id: "doxorubicin_sodium-bicarbonate",
    drugA: "Doxorubicin",
    drugB: "Sodium Bicarbonate",
    status: "incompatible",
    confidenceScore: 86,
    type: "chemical",
    severity: "major",
    mechanism:
      "Doxorubicin is unstable at alkaline pH and degrades rapidly (color change/precipitation) when exposed to bicarbonate or other alkaline solutions.",
    recommendedAction: "Never mix or co-infuse with alkaline solutions. Prepare and administer per vesicant/hazardous drug handling protocol on a dedicated line.",
    alternativeAdministration: "Use a dedicated central line; if extravasation risk is a concern, follow institutional vesicant extravasation protocol rather than altering diluent.",
    flushRecommendation: "Flush with 0.9% Sodium Chloride or D5W before and after infusion; never flush with bicarbonate-containing fluids.",
    ySiteCompatible: false,
    concentrationDependent: false,
    careSettings: ["oncology"],
    careSettingNotes: { oncology: "Vesicant - confirm line patency before infusion and monitor closely for extravasation." },
    references: [{ source: "Trissel's IV Compatibility", citation: "Doxorubicin monograph" }],
    lastReviewed: "2025-03-22",
  },
  {
    id: "morphine_ondansetron",
    drugA: "Morphine Sulfate",
    drugB: "Ondansetron",
    status: "compatible",
    confidenceScore: 84,
    type: "physical",
    severity: "minor",
    mechanism:
      "Commonly co-administered for pain and nausea management (e.g., PCA settings, post-operative care); published Y-site studies show no visible incompatibility at usual clinical concentrations.",
    recommendedAction: "Y-site co-administration is acceptable at standard concentrations; monitor for sedation given morphine's CNS depressant effect combined with ondansetron.",
    alternativeAdministration: "No special alternative route required for standard dosing.",
    flushRecommendation: "Routine flush with 0.9% Sodium Chloride is sufficient between unrelated infusions.",
    ySiteCompatible: true,
    concentrationDependent: false,
    careSettings: ["icu", "oncology", "general", "pediatrics"],
    references: [{ source: "Trissel's IV Compatibility", citation: "Morphine-ondansetron Y-site data" }],
    lastReviewed: "2025-02-14",
  },
  {
    id: "potassium-chloride_insulin-regular",
    drugA: "Potassium Chloride",
    drugB: "Insulin Regular (Human)",
    status: "caution",
    confidenceScore: 72,
    type: "therapeutic",
    severity: "moderate",
    mechanism:
      "No direct physical/chemical incompatibility, but insulin drives potassium intracellularly; concurrent or sequential administration (e.g., in DKA management) requires tight coordination to avoid rebound hypokalemia or hyperkalemia.",
    recommendedAction: "Physically compatible for co-infusion where clinically indicated (e.g., DKA protocols), but monitor serum potassium closely and adjust per institutional protocol.",
    alternativeAdministration: "Use protocol-driven, separately titratable infusions in DKA management so each can be adjusted independently.",
    flushRecommendation: "Standard flush practice applies; no special flush requirement beyond routine line care.",
    ySiteCompatible: true,
    concentrationDependent: true,
    careSettings: ["icu", "pediatrics", "general"],
    references: [{ source: "Micromedex", citation: "Potassium chloride-insulin coordination guidance" }],
    lastReviewed: "2025-01-19",
  },
  {
    id: "norepinephrine_sodium-bicarbonate",
    drugA: "Norepinephrine",
    drugB: "Sodium Bicarbonate",
    status: "incompatible",
    confidenceScore: 89,
    type: "chemical",
    severity: "major",
    mechanism:
      "Like other catecholamines, norepinephrine is rapidly oxidized and inactivated in alkaline solutions such as sodium bicarbonate, reducing vasopressor potency unpredictably.",
    recommendedAction: "Never mix or co-infuse in the same line. Use dedicated, clearly labeled vasopressor access.",
    alternativeAdministration: "Administer bicarbonate through a separate lumen or peripheral line distinct from the norepinephrine infusion.",
    flushRecommendation: "Flush thoroughly with 0.9% Sodium Chloride if line sharing is unavoidable in an emergency.",
    ySiteCompatible: false,
    concentrationDependent: false,
    careSettings: ["icu"],
    references: [{ source: "Trissel's IV Compatibility", citation: "Norepinephrine monograph" }],
    lastReviewed: "2025-06-30",
  },
  {
    id: "pantoprazole_multivitamin",
    drugA: "Pantoprazole",
    drugB: "Sodium Chloride 0.9%",
    status: "compatible",
    confidenceScore: 91,
    type: "physical",
    severity: "minor",
    mechanism:
      "Pantoprazole is stable when reconstituted and diluted in 0.9% Sodium Chloride within the manufacturer-specified concentration and time window.",
    recommendedAction: "Administer as a standalone infusion in 0.9% Sodium Chloride within the stability window (typically infuse within a few hours of reconstitution).",
    alternativeAdministration: "No alternative administration route typically required for standard dosing.",
    flushRecommendation: "Flush line before and after with 0.9% Sodium Chloride, especially before/after co-administered incompatible drugs.",
    ySiteCompatible: "conditional",
    ySiteNotes: "Avoid Y-site with drugs requiring acidic diluents; verify institutional chart for specific pairs.",
    concentrationDependent: true,
    careSettings: ["icu", "general"],
    references: [{ source: "ASHP", citation: "Pantoprazole IV stability data" }],
    lastReviewed: "2025-07-27",
  },
  {
    id: "labetalol_furosemide",
    drugA: "Labetalol",
    drugB: "Furosemide",
    status: "caution",
    confidenceScore: 65,
    type: "physical",
    severity: "minor",
    mechanism:
      "Limited published Y-site compatibility data exist for this specific pair; theoretical pH mismatch (furosemide alkaline vs. labetalol acidic) raises a precipitation concern similar to other alkaline-diluent drugs, but confirmed institutional or literature data are sparse.",
    recommendedAction: "Treat as limited-data / use with caution: prefer separate lines until institution-specific compatibility testing or updated literature confirms safety.",
    alternativeAdministration: "Administer sequentially with a flush between doses if a single lumen must be used.",
    flushRecommendation: "Flush with 0.9% Sodium Chloride between administrations.",
    ySiteCompatible: "conditional",
    concentrationDependent: false,
    careSettings: ["icu", "general"],
    references: [{ source: "Micromedex", citation: "Labetalol compatibility data (limited)" }],
    lastReviewed: "2024-12-05",
  },
];
